name: go ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
  gosec:
      name: scanner
      runs-on: ubuntu-latest
      needs: [golangci]
      env:
        GO111MODULE: on
      steps:
        - name: Checkout Source
          uses: actions/checkout@v3
        - name: Run Gosec Security Scanner
          uses: securego/gosec@master
          with:
            args: ./...
  build:
    name: build
    runs-on: ubuntu-latest
    needs: [gosec]
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag password-generator:$(date +%s)